language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

install:
  - go get -v "golang.org/x/net/context"
  - go get -v "github.com/coreos/etcd/client"
  - go get -v "github.com/Sirupsen/logrus"

script:
  - go test ./... -cover
