// Code generated by protoc-gen-go.
// source: errors.proto
// DO NOT EDIT!

/*
Package platform is a generated protocol buffer package.

It is generated from these files:
	errors.proto
	service.proto

It has these top-level messages:
*/
package platform

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

func init() {
}
